const vseZbozi = {
  paprikaCervena: {
    name: "Paprika červená",
    id: 0,
    src: "./img/Paprika_cervena.jpg",
    alt: "čerstvá červená paprika na dřevěném prkénku",
    cost: 25,
  },
  paprikaZluta: {
    name: "Paprika žlutá",
    id: 1,
    src: "./img/Paprika_zluta.jpg",
    alt: "čerstvá žlutá paprika na dřevěném prkénku",
    cost: 26,
  },
  paprikaZelena: {
    name: "Paprika zelená",
    id: 2,
    src: "./img/Paprika_zelena.jpg",
    alt: "čerstvá zelená paprika na dřevěném prkénku",
    cost: 23,
  },
  cesnek: {
    name: "Česnek",
    id: 3,
    src: "./img/Cesnek.jpg",
    alt: "palice suchého česneku na dřevěném prkénku",
    cost: 10,
  },
  banan: {
    name: "Banán",
    id: 4,
    src: "./img/Banan.jpg",
    alt: "banán na dřevěném prkénku",
    cost: 30,
  },
  batat: {
    name: "Batát",
    id: 5,
    src: "./img/Batat.jpg",
    alt: "batát na dřevěném prkénku",
    cost: 28,
  },
  brambora: {
    name: "Brambora",
    id: 6,
    src: "./img/Brambora.jpg",
    alt: "hlíza bramboru na dřevěném prkénku",
    cost: 20,
  },
  cibule: {
    name: "Cibule",
    id: 7,
    src: "./img/Cibule.jpg",
    alt: "palice cibule na dřevěném prkénku",
    cost: 20,
  },
  citron: {
    name: "Citrón",
    id: 8,
    src: "./img/Citron.jpg",
    alt: "citrón na dřevěném prkénku",
    cost: 26,
  },
  jablkoCervene: {
    name: "Jablko Červené",
    id: 9,
    src: "./img/Jablko_Cervene.jpg",
    alt: "červené jablko na dřevěném prkénku",
    cost: 26,
  },
  jablkoZelene: {
    name: "Jablko Zelené",
    id: 10,
    src: "./img/Jablko_Zelene.jpg",
    alt: "Zelené jablko na dřevěném prkénku",
    cost: 26,
  },
  mrkev: {
    name: "Mrkev",
    id: 11,
    src: "./img/Mrkev.jpg",
    alt: "kořen mrkve na dřevěném prkénku",
    cost: 26,
  },
  petrzel: {
    name: "Petržel",
    id: 12,
    src: "./img/Petrzel.jpg",
    alt: "kořen petržele na dřevěném prkénku",
    cost: 26,
  },
  pomeranc: {
    name: "Pomeranč",
    id: 13,
    src: "./img/Pomeranc.jpg",
    alt: "pomeranč na dřevěném prkénku",
    cost: 26,
  },
  rajce: {
    name: "Rajče",
    id: 14,
    src: "./img/Rajce.jpg",
    alt: "plod rajčete na dřevěném prkénku",
    cost: 26,
  },
  vejce: {
    name: "Vejce",
    id: 15,
    src: "./img/Vejce.jpg",
    alt: "vejce na dřevěném prkénku",
    cost: 26,
  },
};

export default vseZbozi;